cc_library(
    name = "communicator",
    srcs = ["communicator.cpp"],
    hdrs = ["communicator.h"],
    deps = ["//common:util", "//common:tree", "//kvstore:kvstore", "@spdlog_repo//:spdlog_lib", "//jsontool:jsontool" , "@protobuf_repo//:protobuf"],
    visibility = ["//visibility:public"]
)