cc_library(
    name = "communicator",
    srcs = ["communicator.cpp"],
    hdrs = ["communicator.h"],
    deps = ["//kvstore:kvstore", "@spdlog_repo//:spdlog_lib", "//jsontool:jsontool"],
    visibility = ["//visibility:public"]
)